// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type AddUploadPartRequest struct {
	// The ID of the Upload.
	//
	UploadID             string                          `pathParam:"style=simple,explode=false,name=upload_id"`
	AddUploadPartRequest components.AddUploadPartRequest `request:"mediaType=multipart/form-data"`
}

func (o *AddUploadPartRequest) GetUploadID() string {
	if o == nil {
		return ""
	}
	return o.UploadID
}

func (o *AddUploadPartRequest) GetAddUploadPartRequest() components.AddUploadPartRequest {
	if o == nil {
		return components.AddUploadPartRequest{}
	}
	return o.AddUploadPartRequest
}

type AddUploadPartResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	UploadPart *components.UploadPart
}

func (o *AddUploadPartResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AddUploadPartResponse) GetUploadPart() *components.UploadPart {
	if o == nil {
		return nil
	}
	return o.UploadPart
}
