// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type CancelVectorStoreFileBatchRequest struct {
	// The ID of the vector store that the file batch belongs to.
	VectorStoreID string `pathParam:"style=simple,explode=false,name=vector_store_id"`
	// The ID of the file batch to cancel.
	BatchID string `pathParam:"style=simple,explode=false,name=batch_id"`
}

func (o *CancelVectorStoreFileBatchRequest) GetVectorStoreID() string {
	if o == nil {
		return ""
	}
	return o.VectorStoreID
}

func (o *CancelVectorStoreFileBatchRequest) GetBatchID() string {
	if o == nil {
		return ""
	}
	return o.BatchID
}

type CancelVectorStoreFileBatchResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	VectorStoreFileBatchObject *components.VectorStoreFileBatchObject
}

func (o *CancelVectorStoreFileBatchResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CancelVectorStoreFileBatchResponse) GetVectorStoreFileBatchObject() *components.VectorStoreFileBatchObject {
	if o == nil {
		return nil
	}
	return o.VectorStoreFileBatchObject
}
