// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type CreateProjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Project created successfully.
	Project *components.Project
}

func (o *CreateProjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateProjectResponse) GetProject() *components.Project {
	if o == nil {
		return nil
	}
	return o.Project
}
