// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type CreateEmbeddingResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	CreateEmbeddingResponse *components.CreateEmbeddingResponse
}

func (o *CreateEmbeddingResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateEmbeddingResponse) GetCreateEmbeddingResponse() *components.CreateEmbeddingResponse {
	if o == nil {
		return nil
	}
	return o.CreateEmbeddingResponse
}
