// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type CreateCompletionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	CreateCompletionResponse *components.CreateCompletionResponse
}

func (o *CreateCompletionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateCompletionResponse) GetCreateCompletionResponse() *components.CreateCompletionResponse {
	if o == nil {
		return nil
	}
	return o.CreateCompletionResponse
}
