// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type CreateProjectUserRequest struct {
	// The ID of the project.
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
	// The project user create request payload.
	ProjectUserCreateRequest components.ProjectUserCreateRequest `request:"mediaType=application/json"`
}

func (o *CreateProjectUserRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *CreateProjectUserRequest) GetProjectUserCreateRequest() components.ProjectUserCreateRequest {
	if o == nil {
		return components.ProjectUserCreateRequest{}
	}
	return o.ProjectUserCreateRequest
}

type CreateProjectUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// User added to project successfully.
	ProjectUser *components.ProjectUser
}

func (o *CreateProjectUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateProjectUserResponse) GetProjectUser() *components.ProjectUser {
	if o == nil {
		return nil
	}
	return o.ProjectUser
}
