// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type CreateVectorStoreFileBatchRequest struct {
	// The ID of the vector store for which to create a File Batch.
	//
	VectorStoreID                     string                                       `pathParam:"style=simple,explode=false,name=vector_store_id"`
	CreateVectorStoreFileBatchRequest components.CreateVectorStoreFileBatchRequest `request:"mediaType=application/json"`
}

func (o *CreateVectorStoreFileBatchRequest) GetVectorStoreID() string {
	if o == nil {
		return ""
	}
	return o.VectorStoreID
}

func (o *CreateVectorStoreFileBatchRequest) GetCreateVectorStoreFileBatchRequest() components.CreateVectorStoreFileBatchRequest {
	if o == nil {
		return components.CreateVectorStoreFileBatchRequest{}
	}
	return o.CreateVectorStoreFileBatchRequest
}

type CreateVectorStoreFileBatchResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	VectorStoreFileBatchObject *components.VectorStoreFileBatchObject
}

func (o *CreateVectorStoreFileBatchResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateVectorStoreFileBatchResponse) GetVectorStoreFileBatchObject() *components.VectorStoreFileBatchObject {
	if o == nil {
		return nil
	}
	return o.VectorStoreFileBatchObject
}
