// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type CreateImageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ImagesResponse *components.ImagesResponse
}

func (o *CreateImageResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateImageResponse) GetImagesResponse() *components.ImagesResponse {
	if o == nil {
		return nil
	}
	return o.ImagesResponse
}
