// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type CreateVectorStoreResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	VectorStoreObject *components.VectorStoreObject
}

func (o *CreateVectorStoreResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateVectorStoreResponse) GetVectorStoreObject() *components.VectorStoreObject {
	if o == nil {
		return nil
	}
	return o.VectorStoreObject
}
