// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type CreateAssistantResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AssistantObject *components.AssistantObject
}

func (o *CreateAssistantResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateAssistantResponse) GetAssistantObject() *components.AssistantObject {
	if o == nil {
		return nil
	}
	return o.AssistantObject
}
