// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type DeleteFileRequest struct {
	// The ID of the file to use for this request.
	FileID string `pathParam:"style=simple,explode=false,name=file_id"`
}

func (o *DeleteFileRequest) GetFileID() string {
	if o == nil {
		return ""
	}
	return o.FileID
}

type DeleteFileResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DeleteFileResponse *components.DeleteFileResponse
}

func (o *DeleteFileResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteFileResponse) GetDeleteFileResponse() *components.DeleteFileResponse {
	if o == nil {
		return nil
	}
	return o.DeleteFileResponse
}
