// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type DeleteInviteRequest struct {
	// The ID of the invite to delete.
	InviteID string `pathParam:"style=simple,explode=false,name=invite_id"`
}

func (o *DeleteInviteRequest) GetInviteID() string {
	if o == nil {
		return ""
	}
	return o.InviteID
}

type DeleteInviteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Invite deleted successfully.
	InviteDeleteResponse *components.InviteDeleteResponse
}

func (o *DeleteInviteResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteInviteResponse) GetInviteDeleteResponse() *components.InviteDeleteResponse {
	if o == nil {
		return nil
	}
	return o.InviteDeleteResponse
}
