// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type DeleteProjectServiceAccountRequest struct {
	// The ID of the project.
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
	// The ID of the service account.
	ServiceAccountID string `pathParam:"style=simple,explode=false,name=service_account_id"`
}

func (o *DeleteProjectServiceAccountRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *DeleteProjectServiceAccountRequest) GetServiceAccountID() string {
	if o == nil {
		return ""
	}
	return o.ServiceAccountID
}

type DeleteProjectServiceAccountResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Project service account deleted successfully.
	ProjectServiceAccountDeleteResponse *components.ProjectServiceAccountDeleteResponse
}

func (o *DeleteProjectServiceAccountResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteProjectServiceAccountResponse) GetProjectServiceAccountDeleteResponse() *components.ProjectServiceAccountDeleteResponse {
	if o == nil {
		return nil
	}
	return o.ProjectServiceAccountDeleteResponse
}
