// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type DeleteThreadRequest struct {
	// The ID of the thread to delete.
	ThreadID string `pathParam:"style=simple,explode=false,name=thread_id"`
}

func (o *DeleteThreadRequest) GetThreadID() string {
	if o == nil {
		return ""
	}
	return o.ThreadID
}

type DeleteThreadResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DeleteThreadResponse *components.DeleteThreadResponse
}

func (o *DeleteThreadResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteThreadResponse) GetDeleteThreadResponse() *components.DeleteThreadResponse {
	if o == nil {
		return nil
	}
	return o.DeleteThreadResponse
}
