// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type DownloadFileRequest struct {
	// The ID of the file to use for this request.
	FileID string `pathParam:"style=simple,explode=false,name=file_id"`
}

func (o *DownloadFileRequest) GetFileID() string {
	if o == nil {
		return ""
	}
	return o.FileID
}

type DownloadFileResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	String *string
}

func (o *DownloadFileResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DownloadFileResponse) GetString() *string {
	if o == nil {
		return nil
	}
	return o.String
}
