// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type GetAssistantRequest struct {
	// The ID of the assistant to retrieve.
	AssistantID string `pathParam:"style=simple,explode=false,name=assistant_id"`
}

func (o *GetAssistantRequest) GetAssistantID() string {
	if o == nil {
		return ""
	}
	return o.AssistantID
}

type GetAssistantResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AssistantObject *components.AssistantObject
}

func (o *GetAssistantResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetAssistantResponse) GetAssistantObject() *components.AssistantObject {
	if o == nil {
		return nil
	}
	return o.AssistantObject
}
