// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type GetMessageRequest struct {
	// The ID of the [thread](/docs/api-reference/threads) to which this message belongs.
	ThreadID string `pathParam:"style=simple,explode=false,name=thread_id"`
	// The ID of the message to retrieve.
	MessageID string `pathParam:"style=simple,explode=false,name=message_id"`
}

func (o *GetMessageRequest) GetThreadID() string {
	if o == nil {
		return ""
	}
	return o.ThreadID
}

func (o *GetMessageRequest) GetMessageID() string {
	if o == nil {
		return ""
	}
	return o.MessageID
}

type GetMessageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	MessageObject *components.MessageObject
}

func (o *GetMessageResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetMessageResponse) GetMessageObject() *components.MessageObject {
	if o == nil {
		return nil
	}
	return o.MessageObject
}
