// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type GetRunRequest struct {
	// The ID of the [thread](/docs/api-reference/threads) that was run.
	ThreadID string `pathParam:"style=simple,explode=false,name=thread_id"`
	// The ID of the run to retrieve.
	RunID string `pathParam:"style=simple,explode=false,name=run_id"`
}

func (o *GetRunRequest) GetThreadID() string {
	if o == nil {
		return ""
	}
	return o.ThreadID
}

func (o *GetRunRequest) GetRunID() string {
	if o == nil {
		return ""
	}
	return o.RunID
}

type GetRunResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	RunObject *components.RunObject
}

func (o *GetRunResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetRunResponse) GetRunObject() *components.RunObject {
	if o == nil {
		return nil
	}
	return o.RunObject
}
