// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type GetThreadRequest struct {
	// The ID of the thread to retrieve.
	ThreadID string `pathParam:"style=simple,explode=false,name=thread_id"`
}

func (o *GetThreadRequest) GetThreadID() string {
	if o == nil {
		return ""
	}
	return o.ThreadID
}

type GetThreadResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ThreadObject *components.ThreadObject
}

func (o *GetThreadResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetThreadResponse) GetThreadObject() *components.ThreadObject {
	if o == nil {
		return nil
	}
	return o.ThreadObject
}
