// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/internal/utils"
	"github.com/jamelt/openai-api/models/components"
)

type ListPaginatedFineTuningJobsRequest struct {
	// Identifier for the last job from the previous pagination request.
	After *string `queryParam:"style=form,explode=true,name=after"`
	// Number of fine-tuning jobs to retrieve.
	Limit *int64 `default:"20" queryParam:"style=form,explode=true,name=limit"`
}

func (l ListPaginatedFineTuningJobsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListPaginatedFineTuningJobsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListPaginatedFineTuningJobsRequest) GetAfter() *string {
	if o == nil {
		return nil
	}
	return o.After
}

func (o *ListPaginatedFineTuningJobsRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

type ListPaginatedFineTuningJobsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ListPaginatedFineTuningJobsResponse *components.ListPaginatedFineTuningJobsResponse
}

func (o *ListPaginatedFineTuningJobsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListPaginatedFineTuningJobsResponse) GetListPaginatedFineTuningJobsResponse() *components.ListPaginatedFineTuningJobsResponse {
	if o == nil {
		return nil
	}
	return o.ListPaginatedFineTuningJobsResponse
}
