// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/jamelt/openai-api/internal/utils"
	"github.com/jamelt/openai-api/models/components"
)

// QueryParamOrder - Sort order by the `created_at` timestamp of the objects. `asc` for ascending order and `desc` for descending order.
type QueryParamOrder string

const (
	QueryParamOrderAsc  QueryParamOrder = "asc"
	QueryParamOrderDesc QueryParamOrder = "desc"
)

func (e QueryParamOrder) ToPointer() *QueryParamOrder {
	return &e
}
func (e *QueryParamOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = QueryParamOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamOrder: %v", v)
	}
}

type ListFilesRequest struct {
	// Only return files with the given purpose.
	Purpose *string `queryParam:"style=form,explode=true,name=purpose"`
	// A limit on the number of objects to be returned. Limit can range between 1 and 10,000, and the default is 10,000.
	//
	Limit *int64 `default:"10000" queryParam:"style=form,explode=true,name=limit"`
	// Sort order by the `created_at` timestamp of the objects. `asc` for ascending order and `desc` for descending order.
	//
	Order *QueryParamOrder `default:"desc" queryParam:"style=form,explode=true,name=order"`
	// A cursor for use in pagination. `after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with obj_foo, your subsequent call can include after=obj_foo in order to fetch the next page of the list.
	//
	After *string `queryParam:"style=form,explode=true,name=after"`
}

func (l ListFilesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListFilesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListFilesRequest) GetPurpose() *string {
	if o == nil {
		return nil
	}
	return o.Purpose
}

func (o *ListFilesRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListFilesRequest) GetOrder() *QueryParamOrder {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *ListFilesRequest) GetAfter() *string {
	if o == nil {
		return nil
	}
	return o.After
}

type ListFilesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	ListFilesResponse *components.ListFilesResponse
}

func (o *ListFilesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListFilesResponse) GetListFilesResponse() *components.ListFilesResponse {
	if o == nil {
		return nil
	}
	return o.ListFilesResponse
}
