// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/internal/utils"
	"github.com/jamelt/openai-api/models/components"
)

type ListProjectServiceAccountsRequest struct {
	// The ID of the project.
	ProjectID string `pathParam:"style=simple,explode=false,name=project_id"`
	// A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 20.
	//
	Limit *int64 `default:"20" queryParam:"style=form,explode=true,name=limit"`
	// A cursor for use in pagination. `after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with obj_foo, your subsequent call can include after=obj_foo in order to fetch the next page of the list.
	//
	After *string `queryParam:"style=form,explode=true,name=after"`
}

func (l ListProjectServiceAccountsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListProjectServiceAccountsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListProjectServiceAccountsRequest) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

func (o *ListProjectServiceAccountsRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListProjectServiceAccountsRequest) GetAfter() *string {
	if o == nil {
		return nil
	}
	return o.After
}

type ListProjectServiceAccountsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Project service accounts listed successfully.
	ProjectServiceAccountListResponse *components.ProjectServiceAccountListResponse
}

func (o *ListProjectServiceAccountsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ListProjectServiceAccountsResponse) GetProjectServiceAccountListResponse() *components.ProjectServiceAccountListResponse {
	if o == nil {
		return nil
	}
	return o.ProjectServiceAccountListResponse
}
