// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type ModifyRunRequest struct {
	// The ID of the [thread](/docs/api-reference/threads) that was run.
	ThreadID string `pathParam:"style=simple,explode=false,name=thread_id"`
	// The ID of the run to modify.
	RunID            string                      `pathParam:"style=simple,explode=false,name=run_id"`
	ModifyRunRequest components.ModifyRunRequest `request:"mediaType=application/json"`
}

func (o *ModifyRunRequest) GetThreadID() string {
	if o == nil {
		return ""
	}
	return o.ThreadID
}

func (o *ModifyRunRequest) GetRunID() string {
	if o == nil {
		return ""
	}
	return o.RunID
}

func (o *ModifyRunRequest) GetModifyRunRequest() components.ModifyRunRequest {
	if o == nil {
		return components.ModifyRunRequest{}
	}
	return o.ModifyRunRequest
}

type ModifyRunResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	RunObject *components.RunObject
}

func (o *ModifyRunResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ModifyRunResponse) GetRunObject() *components.RunObject {
	if o == nil {
		return nil
	}
	return o.RunObject
}
