// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type RetrieveUserRequest struct {
	// The ID of the user.
	UserID string `pathParam:"style=simple,explode=false,name=user_id"`
}

func (o *RetrieveUserRequest) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}

type RetrieveUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// User retrieved successfully.
	User *components.User
}

func (o *RetrieveUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RetrieveUserResponse) GetUser() *components.User {
	if o == nil {
		return nil
	}
	return o.User
}
