// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/jamelt/openai-api/models/components"
)

type RetrieveInviteRequest struct {
	// The ID of the invite to retrieve.
	InviteID string `pathParam:"style=simple,explode=false,name=invite_id"`
}

func (o *RetrieveInviteRequest) GetInviteID() string {
	if o == nil {
		return ""
	}
	return o.InviteID
}

type RetrieveInviteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Invite retrieved successfully.
	Invite *components.Invite
}

func (o *RetrieveInviteResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RetrieveInviteResponse) GetInvite() *components.Invite {
	if o == nil {
		return nil
	}
	return o.Invite
}
