// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AuditLogActorSession - The session in which the audit logged action was performed.
type AuditLogActorSession struct {
	// The user who performed the audit logged action.
	User *AuditLogActorUser `json:"user,omitempty"`
	// The IP address from which the action was performed.
	IPAddress *string `json:"ip_address,omitempty"`
}

func (o *AuditLogActorSession) GetUser() *AuditLogActorUser {
	if o == nil {
		return nil
	}
	return o.User
}

func (o *AuditLogActorSession) GetIPAddress() *string {
	if o == nil {
		return nil
	}
	return o.IPAddress
}
