// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AuditLogActorUser - The user who performed the audit logged action.
type AuditLogActorUser struct {
	// The user id.
	ID *string `json:"id,omitempty"`
	// The user email.
	Email *string `json:"email,omitempty"`
}

func (o *AuditLogActorUser) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AuditLogActorUser) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}
