// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AuditLogActorServiceAccount - The service account that performed the audit logged action.
type AuditLogActorServiceAccount struct {
	// The service account id.
	ID *string `json:"id,omitempty"`
}

func (o *AuditLogActorServiceAccount) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}
