// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/jamelt/openai-api/internal/utils"
)

type ChatCompletionRequestSystemMessageContentPartType string

const (
	ChatCompletionRequestSystemMessageContentPartTypeChatCompletionRequestMessageContentPartText ChatCompletionRequestSystemMessageContentPartType = "ChatCompletionRequestMessageContentPartText"
)

type ChatCompletionRequestSystemMessageContentPart struct {
	ChatCompletionRequestMessageContentPartText *ChatCompletionRequestMessageContentPartText

	Type ChatCompletionRequestSystemMessageContentPartType
}

func CreateChatCompletionRequestSystemMessageContentPartChatCompletionRequestMessageContentPartText(chatCompletionRequestMessageContentPartText ChatCompletionRequestMessageContentPartText) ChatCompletionRequestSystemMessageContentPart {
	typ := ChatCompletionRequestSystemMessageContentPartTypeChatCompletionRequestMessageContentPartText

	return ChatCompletionRequestSystemMessageContentPart{
		ChatCompletionRequestMessageContentPartText: &chatCompletionRequestMessageContentPartText,
		Type: typ,
	}
}

func (u *ChatCompletionRequestSystemMessageContentPart) UnmarshalJSON(data []byte) error {

	var chatCompletionRequestMessageContentPartText ChatCompletionRequestMessageContentPartText = ChatCompletionRequestMessageContentPartText{}
	if err := utils.UnmarshalJSON(data, &chatCompletionRequestMessageContentPartText, "", true, true); err == nil {
		u.ChatCompletionRequestMessageContentPartText = &chatCompletionRequestMessageContentPartText
		u.Type = ChatCompletionRequestSystemMessageContentPartTypeChatCompletionRequestMessageContentPartText
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ChatCompletionRequestSystemMessageContentPart", string(data))
}

func (u ChatCompletionRequestSystemMessageContentPart) MarshalJSON() ([]byte, error) {
	if u.ChatCompletionRequestMessageContentPartText != nil {
		return utils.MarshalJSON(u.ChatCompletionRequestMessageContentPartText, "", true)
	}

	return nil, errors.New("could not marshal union type ChatCompletionRequestSystemMessageContentPart: all fields are null")
}
