// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CreateTranscriptionResponseJSON - Represents a transcription response returned by model, based on the provided input.
type CreateTranscriptionResponseJSON struct {
	// The transcribed text.
	Text string `json:"text"`
}

func (o *CreateTranscriptionResponseJSON) GetText() string {
	if o == nil {
		return ""
	}
	return o.Text
}
