// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DeleteModelResponse struct {
	ID      string `json:"id"`
	Deleted bool   `json:"deleted"`
	Object  string `json:"object"`
}

func (o *DeleteModelResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *DeleteModelResponse) GetDeleted() bool {
	if o == nil {
		return false
	}
	return o.Deleted
}

func (o *DeleteModelResponse) GetObject() string {
	if o == nil {
		return ""
	}
	return o.Object
}
