// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type DeleteThreadResponseObject string

const (
	DeleteThreadResponseObjectThreadDeleted DeleteThreadResponseObject = "thread.deleted"
)

func (e DeleteThreadResponseObject) ToPointer() *DeleteThreadResponseObject {
	return &e
}
func (e *DeleteThreadResponseObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "thread.deleted":
		*e = DeleteThreadResponseObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DeleteThreadResponseObject: %v", v)
	}
}

type DeleteThreadResponse struct {
	ID      string                     `json:"id"`
	Deleted bool                       `json:"deleted"`
	Object  DeleteThreadResponseObject `json:"object"`
}

func (o *DeleteThreadResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *DeleteThreadResponse) GetDeleted() bool {
	if o == nil {
		return false
	}
	return o.Deleted
}

func (o *DeleteThreadResponse) GetObject() DeleteThreadResponseObject {
	if o == nil {
		return DeleteThreadResponseObject("")
	}
	return o.Object
}
