// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Error struct {
	Code    *string `json:"code"`
	Message string  `json:"message"`
	Param   *string `json:"param"`
	Type    string  `json:"type"`
}

func (o *Error) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *Error) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *Error) GetParam() *string {
	if o == nil {
		return nil
	}
	return o.Param
}

func (o *Error) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}
