// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// Metrics at the step number during the fine-tuning job.
type Metrics struct {
	Step                       *float64 `json:"step,omitempty"`
	TrainLoss                  *float64 `json:"train_loss,omitempty"`
	TrainMeanTokenAccuracy     *float64 `json:"train_mean_token_accuracy,omitempty"`
	ValidLoss                  *float64 `json:"valid_loss,omitempty"`
	ValidMeanTokenAccuracy     *float64 `json:"valid_mean_token_accuracy,omitempty"`
	FullValidLoss              *float64 `json:"full_valid_loss,omitempty"`
	FullValidMeanTokenAccuracy *float64 `json:"full_valid_mean_token_accuracy,omitempty"`
}

func (o *Metrics) GetStep() *float64 {
	if o == nil {
		return nil
	}
	return o.Step
}

func (o *Metrics) GetTrainLoss() *float64 {
	if o == nil {
		return nil
	}
	return o.TrainLoss
}

func (o *Metrics) GetTrainMeanTokenAccuracy() *float64 {
	if o == nil {
		return nil
	}
	return o.TrainMeanTokenAccuracy
}

func (o *Metrics) GetValidLoss() *float64 {
	if o == nil {
		return nil
	}
	return o.ValidLoss
}

func (o *Metrics) GetValidMeanTokenAccuracy() *float64 {
	if o == nil {
		return nil
	}
	return o.ValidMeanTokenAccuracy
}

func (o *Metrics) GetFullValidLoss() *float64 {
	if o == nil {
		return nil
	}
	return o.FullValidLoss
}

func (o *Metrics) GetFullValidMeanTokenAccuracy() *float64 {
	if o == nil {
		return nil
	}
	return o.FullValidMeanTokenAccuracy
}

// FineTuningJobCheckpointObject - The object type, which is always "fine_tuning.job.checkpoint".
type FineTuningJobCheckpointObject string

const (
	FineTuningJobCheckpointObjectFineTuningJobCheckpoint FineTuningJobCheckpointObject = "fine_tuning.job.checkpoint"
)

func (e FineTuningJobCheckpointObject) ToPointer() *FineTuningJobCheckpointObject {
	return &e
}
func (e *FineTuningJobCheckpointObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "fine_tuning.job.checkpoint":
		*e = FineTuningJobCheckpointObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FineTuningJobCheckpointObject: %v", v)
	}
}

// FineTuningJobCheckpoint - The `fine_tuning.job.checkpoint` object represents a model checkpoint for a fine-tuning job that is ready to use.
type FineTuningJobCheckpoint struct {
	// The checkpoint identifier, which can be referenced in the API endpoints.
	ID string `json:"id"`
	// The Unix timestamp (in seconds) for when the checkpoint was created.
	CreatedAt int64 `json:"created_at"`
	// The name of the fine-tuned checkpoint model that is created.
	FineTunedModelCheckpoint string `json:"fine_tuned_model_checkpoint"`
	// The step number that the checkpoint was created at.
	StepNumber int64 `json:"step_number"`
	// Metrics at the step number during the fine-tuning job.
	Metrics Metrics `json:"metrics"`
	// The name of the fine-tuning job that this checkpoint was created from.
	FineTuningJobID string `json:"fine_tuning_job_id"`
	// The object type, which is always "fine_tuning.job.checkpoint".
	Object FineTuningJobCheckpointObject `json:"object"`
}

func (o *FineTuningJobCheckpoint) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *FineTuningJobCheckpoint) GetCreatedAt() int64 {
	if o == nil {
		return 0
	}
	return o.CreatedAt
}

func (o *FineTuningJobCheckpoint) GetFineTunedModelCheckpoint() string {
	if o == nil {
		return ""
	}
	return o.FineTunedModelCheckpoint
}

func (o *FineTuningJobCheckpoint) GetStepNumber() int64 {
	if o == nil {
		return 0
	}
	return o.StepNumber
}

func (o *FineTuningJobCheckpoint) GetMetrics() Metrics {
	if o == nil {
		return Metrics{}
	}
	return o.Metrics
}

func (o *FineTuningJobCheckpoint) GetFineTuningJobID() string {
	if o == nil {
		return ""
	}
	return o.FineTuningJobID
}

func (o *FineTuningJobCheckpoint) GetObject() FineTuningJobCheckpointObject {
	if o == nil {
		return FineTuningJobCheckpointObject("")
	}
	return o.Object
}
