// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListAssistantsResponse struct {
	Object  string            `json:"object"`
	Data    []AssistantObject `json:"data"`
	FirstID string            `json:"first_id"`
	LastID  string            `json:"last_id"`
	HasMore bool              `json:"has_more"`
}

func (o *ListAssistantsResponse) GetObject() string {
	if o == nil {
		return ""
	}
	return o.Object
}

func (o *ListAssistantsResponse) GetData() []AssistantObject {
	if o == nil {
		return []AssistantObject{}
	}
	return o.Data
}

func (o *ListAssistantsResponse) GetFirstID() string {
	if o == nil {
		return ""
	}
	return o.FirstID
}

func (o *ListAssistantsResponse) GetLastID() string {
	if o == nil {
		return ""
	}
	return o.LastID
}

func (o *ListAssistantsResponse) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}
