// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListRunStepsResponse struct {
	Object  string          `json:"object"`
	Data    []RunStepObject `json:"data"`
	FirstID string          `json:"first_id"`
	LastID  string          `json:"last_id"`
	HasMore bool            `json:"has_more"`
}

func (o *ListRunStepsResponse) GetObject() string {
	if o == nil {
		return ""
	}
	return o.Object
}

func (o *ListRunStepsResponse) GetData() []RunStepObject {
	if o == nil {
		return []RunStepObject{}
	}
	return o.Data
}

func (o *ListRunStepsResponse) GetFirstID() string {
	if o == nil {
		return ""
	}
	return o.FirstID
}

func (o *ListRunStepsResponse) GetLastID() string {
	if o == nil {
		return ""
	}
	return o.LastID
}

func (o *ListRunStepsResponse) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}
