// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListVectorStoreFilesResponse struct {
	Object  string                  `json:"object"`
	Data    []VectorStoreFileObject `json:"data"`
	FirstID string                  `json:"first_id"`
	LastID  string                  `json:"last_id"`
	HasMore bool                    `json:"has_more"`
}

func (o *ListVectorStoreFilesResponse) GetObject() string {
	if o == nil {
		return ""
	}
	return o.Object
}

func (o *ListVectorStoreFilesResponse) GetData() []VectorStoreFileObject {
	if o == nil {
		return []VectorStoreFileObject{}
	}
	return o.Data
}

func (o *ListVectorStoreFilesResponse) GetFirstID() string {
	if o == nil {
		return ""
	}
	return o.FirstID
}

func (o *ListVectorStoreFilesResponse) GetLastID() string {
	if o == nil {
		return ""
	}
	return o.LastID
}

func (o *ListVectorStoreFilesResponse) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}
