// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ProjectAPIKeyListResponseObject string

const (
	ProjectAPIKeyListResponseObjectList ProjectAPIKeyListResponseObject = "list"
)

func (e ProjectAPIKeyListResponseObject) ToPointer() *ProjectAPIKeyListResponseObject {
	return &e
}
func (e *ProjectAPIKeyListResponseObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		*e = ProjectAPIKeyListResponseObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ProjectAPIKeyListResponseObject: %v", v)
	}
}

type ProjectAPIKeyListResponse struct {
	Object  ProjectAPIKeyListResponseObject `json:"object"`
	Data    []ProjectAPIKey                 `json:"data"`
	FirstID string                          `json:"first_id"`
	LastID  string                          `json:"last_id"`
	HasMore bool                            `json:"has_more"`
}

func (o *ProjectAPIKeyListResponse) GetObject() ProjectAPIKeyListResponseObject {
	if o == nil {
		return ProjectAPIKeyListResponseObject("")
	}
	return o.Object
}

func (o *ProjectAPIKeyListResponse) GetData() []ProjectAPIKey {
	if o == nil {
		return []ProjectAPIKey{}
	}
	return o.Data
}

func (o *ProjectAPIKeyListResponse) GetFirstID() string {
	if o == nil {
		return ""
	}
	return o.FirstID
}

func (o *ProjectAPIKeyListResponse) GetLastID() string {
	if o == nil {
		return ""
	}
	return o.LastID
}

func (o *ProjectAPIKeyListResponse) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}
