// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// StaticChunkingStrategyResponseParamType - Always `static`.
type StaticChunkingStrategyResponseParamType string

const (
	StaticChunkingStrategyResponseParamTypeStatic StaticChunkingStrategyResponseParamType = "static"
)

func (e StaticChunkingStrategyResponseParamType) ToPointer() *StaticChunkingStrategyResponseParamType {
	return &e
}
func (e *StaticChunkingStrategyResponseParamType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "static":
		*e = StaticChunkingStrategyResponseParamType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StaticChunkingStrategyResponseParamType: %v", v)
	}
}

type StaticChunkingStrategyResponseParam struct {
	// Always `static`.
	Type   StaticChunkingStrategyResponseParamType `json:"type"`
	Static StaticChunkingStrategy                  `json:"static"`
}

func (o *StaticChunkingStrategyResponseParam) GetType() StaticChunkingStrategyResponseParamType {
	if o == nil {
		return StaticChunkingStrategyResponseParamType("")
	}
	return o.Type
}

func (o *StaticChunkingStrategyResponseParam) GetStatic() StaticChunkingStrategy {
	if o == nil {
		return StaticChunkingStrategy{}
	}
	return o.Static
}
