// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type UserDeleteResponseObject string

const (
	UserDeleteResponseObjectOrganizationUserDeleted UserDeleteResponseObject = "organization.user.deleted"
)

func (e UserDeleteResponseObject) ToPointer() *UserDeleteResponseObject {
	return &e
}
func (e *UserDeleteResponseObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "organization.user.deleted":
		*e = UserDeleteResponseObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UserDeleteResponseObject: %v", v)
	}
}

type UserDeleteResponse struct {
	Object  UserDeleteResponseObject `json:"object"`
	ID      string                   `json:"id"`
	Deleted bool                     `json:"deleted"`
}

func (o *UserDeleteResponse) GetObject() UserDeleteResponseObject {
	if o == nil {
		return UserDeleteResponseObject("")
	}
	return o.Object
}

func (o *UserDeleteResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UserDeleteResponse) GetDeleted() bool {
	if o == nil {
		return false
	}
	return o.Deleted
}
